Check that `UpgradeCurrentLogger` can't fail future logging calls (#23704)
We assume our logging framework's calls are fallable, and we can safely
ignore failures:


https://github.com/pulumi/pulumi/blob/9fd06c1f63cc96364edc6860452567154846a28c/pkg/cmd/pulumi/stack/secrets.go#L313-L315

This is true only when ignoring one failure doesn't cause another later
down the line. This PR adds a test that replicates the failure we saw in
https://github.com/pulumi/pulumi/actions/runs/27960130119/job/83622152193?pr=23657:

```
=== FAIL: go/auto TestInlineConcurrentUpdateError (3.47s)
    errors_test.go:115:
        	Error Trace:	D:/a/pulumi/pulumi/sdk/go/auto/errors_test.go:115
        	Error:      	Expected nil, but got: auto.autoError***stdout:"Updating (moolumi/testf35f7f5d42ff291c)\n\nView Live: https://app.pulumi.com/moolumi/inline_conflict_error/testf35f7f5d42ff291c/updates/1\n\n", stderr:"error: closing log file: close D:\\a\\pulumi\\pulumi\\home\\logs\\pulumi-20260626T085401-8176.log: file already closed\n", code:1, err:(*fmt.wrapError)(0x2243a6f6a840)***
        	Test:       	TestInlineConcurrentUpdateError
    errors_test.go:119:
        	Error Trace:	D:/a/pulumi/pulumi/sdk/go/auto/errors_test.go:119
        	Error:      	Received unexpected error:
        	            	failed to destroy stack: exit status 1
        	            	code: 1
        	            	stdout: Destroying (moolumi/testf35f7f5d42ff291c)

        	            	stderr: error: [409] Conflict: Another update is currently in progress.
        	            	To learn more about possible reasons and resolution, visit https://www.pulumi.com/docs/support/troubleshooting/common-issues/update-conflicts/

        	Test:       	TestInlineConcurrentUpdateError
        	Messages:   	destroy failed
    errors_test.go:98:
        	Error Trace:	D:/a/pulumi/pulumi/sdk/go/auto/errors_test.go:98
        	            				C:/hostedtoolcache/windows/go/1.26.4/x64/src/runtime/panic.go:694
        	            				C:/hostedtoolcache/windows/go/1.26.4/x64/src/testing/testing.go:1022
        	            				D:/a/pulumi/pulumi/sdk/go/auto/errors_test.go:119
        	Error:      	Expected nil, but got: auto.autoError***stdout:"", stderr:"error: [409] Conflict: Stack has an update in-progress.\n", code:1, err:(*fmt.wrapError)(0x2243a71985c0)***
        	Test:       	TestInlineConcurrentUpdateError
        	Messages:   	failed to remove stack. Resources have leaked.

```

[CI failure
(windows)](https://github.com/pulumi/pulumi/actions/runs/28238658456/job/83660763712)
& [CI failure
(ubuntu)](https://github.com/pulumi/pulumi/actions/runs/28238658456/job/83660763719)
show that the added test actually reproduces the failure.