maybe stop CI failing because coverage data merging fails (#21894)
We sometimes get errors like

```
Run # Merge coverage data from coverage-instrumented binaries
error: merging counters: len(dst)=99 len(src)=2
Error: Process completed with exit code 1.
```

This is very annoying in CI, because it fails runs that have otherwise
completely succeeded. Here we attempt to fix this by calling `go tool
covdata merge` first before trying the conversion.

Note that this is almost completely an idea from Claude Code, because I
couldn't find anything more conclusive on the internet. So it may or may
not work, but it's probably worth a try since it shouldn't really hurt
either way.