Improve invalid credentials error message (#17541)
We're seeing this error from esc
([issue](https://github.com/pulumi/esc/issues/401)) which is confusing
because it recommends `pulumi login` when using `esc login`.
Additionally, rerunning `pulumi login` (or `esc login`) as the message
suggests doesn't actually fix anything. I think a better error message
is to suggest fixing or deleting the invalid credentials file - open to
suggestions though

Testing:
```
❯ go run ./cmd/pulumi login
error: could not determine current cloud: failed to read Pulumi credentials file. Please fix or delete invalid credentials file: '/Users/sean/.pulumi/credentials.json': invalid character 'a' looking for beginning of value
exit status 255
```