avoid duplicate error: refix with `--expect-no-changes`
When printing an error we already prefix it with a `error:` prefix.
Therefore new errors should not include that prefix again, otherwise
we'll end up with a line like:

    error: error: no changes were expected but changes occurred