test(cmd/pulumi): Always use a valid project directory name
Using `t.TempDir()` or a hex-encoded string isn't enough
because the name may start with a number.

This switches all such temporary directories to use:

    $tempDir/test-$random

Where `$tempDir` is managed by the current test.

This will address flaky errors like:

```
=== FAIL: cmd/pulumi TestCreatingStackWithArgsSpecifiedOrgName (0.69s)
    new_test.go:74:
        	Error Trace:	/home/runner/work/pulumi/pulumi/pkg/cmd/pulumi/new_test.go:74
        	Error:      	Received unexpected error:
        	            	'001' is not a valid project name. a project with this name already exists: 001
        	Test:       	TestCreatingStackWithArgsSpecifiedOrgName
```

Because the temporary directory was:

    /tmp/TestCreatingStackWithArgsSpecifiedOrgName963299567/001