Tweak command help
When running an unknown command, for example a misspelled resource, we were printing the command’s help.

We can do a little better and clearly flag the error and suggest a close match.

Before:
```
# should be captialized `Bucket`, not `bucket`
$ pulumi do aws s3 bucket read website-content-d6d1f5d
Functions and resources for the s3 module.

Run 'pulumi do aws s3 <resource/function> --help' for more details on usage.

Usage:
  pulumi do aws s3 [command]

...
```

After:
```
$ pulumi do aws s3 bucket read website-content-d6d1f5d
error: unknown command "bucket" for "pulumi do aws s3"

Did you mean this?
	Bucket
	BucketAbac
	BucketAccelerateConfiguration
	BucketAccelerateConfigurationV2
...
```

Also don’t show the `flags` usage bit  for container commands. They don’t do anything by themselves, but since the way we build our dynamic command tree they are technically runnable.