Make test_output.py less fragile
This test is using `unittest.mock.patch.dict`, but only importing `unittest`, which normally causes a failure `AttributeError: module 'unittest' has no attribute 'mock’`.

We happen to import  `unittest.mock` in `test_deprecated.py`, and so when running the whole test suite (and `test_deprecated.py` runs first) it works.

Make this less fragile by directly importing the patch function.