Add --checksum to `pulumi plugin install`
With non-hex string:
```
$ pulumi plugin install resource gcp 6.35.0 --checksum boom
error: --checksum was not a valid hex string: encoding/hex: invalid byte: U+006F 'o'
```

With the wrong checksum:
```
$ pulumi plugin install resource gcp 6.35.0 --checksum c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d
[resource plugin gcp-6.35.0] installing
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 1s
warning: Error downloading plugin: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
Will retry in 80ms [1/5]
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 1s
warning: Error downloading plugin: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
Will retry in 160ms [2/5]
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 1s
warning: Error downloading plugin: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
Will retry in 320ms [3/5]
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 1s
warning: Error downloading plugin: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
Will retry in 640ms [4/5]
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 1s
warning: Error downloading plugin: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
Will retry in 1.28s [5/5]
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 1s
error: [resource plugin gcp-6.35.0] downloading from : failed to download plugin: gcp-6.35.0: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
```

We need to make the retry-logic here smarter, but at least this _does_ check the checksum.