Use `assert.NoError` rather than `assert.Nil`
Likewise `require.NoError` instead of `require.Nil`, and `assert.Error` rather
than `assert.NotNil`.

The error variants of these functions print the errors nicer for test failures
using `Error()` rather than `GoString()`.

For bail errors this is _much_ better than the `result.Result` days
where we no get errors like:
```
Error:      	Received unexpected error:
            	BAIL: inner error
```
instead of:
```
Error:      	Expected nil, but got: &simpleResult{}
```

Also print the bail error in `TestPlan.Run` so we can see the description of it.