Fix registry template downloads by not passing Accept header
Stop passing Accept: application/x-tar to registry template download
URLs to avoid signature mismatch.

Example error this fixes:

```
 ~/Development/cli-deployment-test λ PULUMI_EXPERIMENTAL=1 ~/go/src/github.com/pulumi/pulumi/bin/pulumi new csharp-documented
error: failed to download from "https://blobs-fnune-review.review-stacks.pulumi-dev.io/private-registry/templates/d5c13739-d452-46d5-a978-1bd79b022439/archive.tar.gz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=reviewStacksSecretRootUser%2F20250721%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250721T152124Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=50cf2d9cf4e2a5164122c07b4bb7085a3314d58b59987c482a9fbde9a0ffd27d": [403] <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>templates/d5c13739-d452-46d5-a978-1bd79b022439/archive.tar.gz</Key><BucketName>private-registry</BucketName><Resource>/private-registry/templates/d5c13739-d452-46d5-a978-1bd79b022439/archive.tar.gz</Resource><RequestId>18544D6CF90F1BBF</RequestId><HostId>dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8</HostId></Error>
```

Fixing this in `pulumi-service` is not wanted because template download
URLs should work e.g. in browsers or clients that don't know to pass
custom headers.