Fix invalid build constrains: `integration_nodejs_test.go`
`tests/integration/integration_nodejs_test.go` does not work when the only flag passed to
it is `nodejs`

```console
$ go test -test.run \^TestPrintfNodeJS\$ -test.v -tags=nodejs
./integration_nodejs_test.go:2131:2: undefined: testConstructProviderPropagation
FAIL	github.com/pulumi/pulumi/tests/integration [build failed]
```

Assuming that `all` -> `nodejs`, and since we know that `nodejs` is never standalone, we
know it is safe to reduce `all || nodejs` to `all`.