Always wrap URNs to unprotect with single quotes (#21760)
Some error messages related to `pulumi state unprotect` don't wrap the
URNs with single quotes, or wrap them with double quotes which can
create interpolation issues if the resource URN contains a `$` sign. In
my case the output was:
```
error: unable to replace resource "urn:pulumi:infra-myproject::infra::fargateApp:Deployment$aws:ecs/cluster:Cluster$aws:ecs/taskDefinition:TaskDefinition::mycluster-task-definition" as part of replacing "urn:pulumi:infra-myproject::infra::fargateApp:Deployment$aws:iam/role:Role::mycluster-execution-role" as it is currently marked for protection. To unprotect the resource, remove the `protect` flag from the resource in your Pulumi program and run `pulumi up`, or use the command:
`pulumi state unprotect "urn:pulumi:infra-myproject::infra::fargateApp:Deployment$aws:ecs/cluster:Cluster$aws:ecs/taskDefinition:TaskDefinition::mycluster-task-definition"`
#                       ^ Double quote: running the command will fail because the $ sign will be interpolated by the shell
```