Addresses UX feedback on the Copilot Error summary feature (#19267)
Fixes https://github.com/pulumi/pulumi.ai/issues/1802

Addresses UX feedback on the _Copilot Error summary feature_ left in
https://github.com/pulumi/pulumi/pull/19206#issuecomment-2804137181

- [x] 2. Add `--coilot` to `destroy`, `preview` and `refresh`
- [x] 3. Move `explainFailure` link down to summary if `--copilot` is
provided and reconcile "ai-generated" / "copilot" terminology.
- [x] 4. Remove duration
- [x] 5. Rename AI-generated _summary_ to Diagnostics / Error summary.

We also do the flag rename from `--copilot-summary` to `--copilot` here,
this change has been made in https://github.com/pulumi/pulumi/pull/19138
too and whichever PR lands first, the other will need to be reconciled.

New

`pulumi up --copilot --yes`


```
...

Diagnostics:
  command:local:Command (errorCommand):
    error: exit status 127: running "nonexistentcommand":
    /bin/sh: nonexistentcommand: command not found

  pulumi:pulumi:Stack (ts-nonexistant-command-dev):
    warning: using pulumi-language-nodejs from $PATH at /opt/homebrew/bin/pulumi-language-nodejs
    error: update failed

Resources:
    1 unchanged

Duration: 2s

Copilot Error Summary ✨:
  Command "nonexistentcommand" not found; check command name or path.

  Would you like additional help with this update?
  https://app.pulumi.com/simon-org/ts-nonexistant-command/dev/updates/45?explainFailure
```

Previous (old behavior):

`pulumi up --copilot-summary --yes`

```
...

Diagnostics:
  command:local:Command (errorCommand):
    error: exit status 127: running "nonexistentcommand":
    /bin/sh: nonexistentcommand: command not found

  pulumi:pulumi:Stack (ts-nonexistant-command-dev):
    warning: using pulumi-language-nodejs from $PATH at /opt/homebrew/bin/pulumi-language-nodejs
    error: update failed

    [Pulumi Copilot] Would you like help with these diagnostics?
    https://app.pulumi.com/simon-org/ts-nonexistant-command/dev/updates/46?explainFailure

Resources:
    1 unchanged

Duration: 2s

AI-generated summary ✨: 1128ms
  Error: Command "nonexistentcommand" not found; check command name or path.
```

Screenshots

New:

<img width="784" alt="image"
src="https://github.com/user-attachments/assets/01df0238-9899-4cff-bf13-06bc7b91e379"
/>



Previous (old behavior):

![Screenshot 2025-04-22 at 12 58
13](https://github.com/user-attachments/assets/702db77e-557e-40a8-9964-0c7f8d3cd52a)