Do not `os.Exit` from `RunCmdFunc` (#18757)
This PR changes how Pulumi's `cobra` commands error, bringing it more
inline with how cobra prefers errors to be handled.

This allows directly testing full cobra commands:

```go
func TestMyNewStuff(t *testing.T) {
	t.Cleanup(captureStdout())
	
	cmd := NewNewCmd()
	cmd.SetArgs("--list-templates")
	err := cmd.Execute()
	assert.NoError(t, err)

	assert.Contains(t, os.Stdout, "my-magic-template")
}
```

All *interesting* edits are made in the first commit:
a49bc00acc81011075dc6a77d09e59e1b1356afe. The second commit
(f54d8db30e5f3ba3790c55ed8a87c91703eabf82) consists exclusively of
changing call sites of `cmd.RunCmdFunc` to accommodate the change in
function signature:

```patch
-		Run: cmd.RunCmdFunc(func(cmd *cobra.Command, args []string) error {
+		RunE: cmd.RunCmdFunc(func(cmd *cobra.Command, args []string) error {
```

This change was motivated by #18627, since `pulumi new --list-templates`
doesn't support unit tests as currently written.

### How this works

Cobra has added two flags to
[`cobra.Command`](https://pkg.go.dev/github.com/spf13/cobra#Command)
that make this possible: `SilenceErrors` and `SilenceUsage`. By setting
both, we get a command that doesn't print anything when something goes
wrong, which is what we want. We can print our own error messages,
formatted as we want them. This PR implements `RunFuncE` to run it's
inner func and print out any appropriate error message *and* return a
bailed error. `main` then checks for an error, exiting non-zero if it
finds one. Because only `main` calls `os.Exit`, we can test entire
functions as unit tests.

### Observable changes

There are two observable changes, both minor:

- We return a different non-zero exit code (255 instead of 1) when we
fail to run a command (for example: `pulumi not-a-command`).
- We don't suggest upgrading `pulumi` to the latest version if a command
fails.

If either of these changes are problematic, we can restore the old
behavior with a little additional complexity.

#### Different error codes

Previously, `pulumi` would return either `255` (-1) (when exiting from
`cmd.RunCmdFunc`) or `1` (when exiting from `main.go`).

```console
$ pulumi aoeiu 
Error: unknown command "aoeiu" for "pulumi"
Run 'pulumi --help' for usage.
$ echo $?
1
```

```console
$ pulumi up
error: no Pulumi.yaml project file found (searching upwards from /Users/ianwahbe/go/src/github.com/pulumi/pulumi). If you have not created a project yet, use `pulumi new` to do so: no project file found
$ echo $?
255
```

After this change, `pulumi` only calls `os.Exit` from `main.go`, so it
always returns the same exit code: `255`. I chose 255 since it's the
most common exit code we return. If we believe that this is a breaking
change for users, we can add back the distinction.

#### Upgrading `pulumi` to latest on failure

Cobra doesn't run `(Persistent)?PostRun` commands on a command where the
`Run(E?)` command fails. The only usage of `(Persistent)?PostRun`
commands in pulumi/pulumi is to display the `checkVersionMsg`. Before
this PR, we were incorrectly simulating `PersistentPostRun` hooks even
when an error was returned. Since this PR lets cobra run it's hooks
natively, we get the native behavior.