[Go] Re-enable l1-stack-reference conformance test (#16838)
By fixing the emitted function for `getOutput` in Go program-gen which
is specific to stack references.

Locally the generated program compiles but I get a runtime error:
```
Error:      	Not equal: 
expected: resource.PropertyValue{V:"plain"}
actual  : resource.PropertyValue{V:(*resource.Secret)(0x14000aa6050)}

Diff:
--- Expected
+++ Actual
@@ -1,3 +1,7 @@
 (resource.PropertyValue) {
- V: (string) (len=5) "plain"
+ V: (*resource.Secret)({
+  Element: (resource.PropertyValue) {
+   V: (string) (len=5) "plain"
+  }
+ })
 }
Messages:   	expected property "plain" to be {plain}
```
However I _think_ this is a local problem with some cached Go SDK
artifacts because when go the implementation of `GetOutput` (from the
generated program) it brings me to a different implementation than the
one I find on latest SDK so testing in CI to make sure

EDIT: fixed by removing hardcoded `/` in the used path when replacing
Pulumi SDK reference

Fixes #16840