avoid duplicate error: prefix with `--expect-no-changes` (#16705)
When printing an error we already prefix it with a `error:` prefix.
Therefore new errors should not include that prefix again, otherwise
we'll end up with a line like:

    error: error: no changes were expected but changes occurred

Just a small cleanup I noticed while testing something else.

(From a quick look at `git grep "\"error:"` I couldn't find other
instances of this)