do: better error messages for `upsert --stateless`
Currently when a user runs `pulumi do upsert --stateless` with some
flags, they can get a confusing error message about the particular
flag not being available, e.g.

```
$ pulumi do random:RandomPassword upsert test --input-file test.yaml --stateless
error: unknown flag: --input-file
```

It's better here to tell the user that `upsert` is not available in
stateless mode, so they don't try to understand why the flag doesn't
exist.  To do that we need to register the command, and then error out
ourselves, as cobra seems to look at the flags first.