Use the Pulumi Registry when resolving `pluginDownloadURLs` for `pulumi plugin install`. (#19762)
This PR adds support for performing a registry based lookup when
installing packages with `pulumi plugin install`.

Examples:

```console
$ pulumi plugin install resource aws-k8s # aws-k8s is a private package
[resource plugin aws-k8s-0.0.21] installing
Downloading plugin: 456.40 KiB / 456.40 KiB [=======================] 100.00% 0s
```

```console
$ pulumi plugin install resource azapi # azapi is in the public registry, but not published by Pulumi
error: 404 HTTP error fetching plugin from https://api.github.com/repos/pulumi/pulumi-azapi/releases/latest. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens
```

```console
$ pulumi plugin install resource dirien/azapi # we need to reference the publisher
[resource plugin azapi-1.12.2] installing
Downloading plugin: 34.66 MiB / 34.66 MiB [=========================] 100.00% 2s
```

---

This PR is broken up into logical commits:

- 8dc83fad768655b7f46bc07d163148fea6388894 adds structured errors to the
backend, and threads them through to the registry. It does not change
behavior.
- 7ca2c610fac608bc4e16bf72efbca8a533a76339 adds an uncalled function to
the public `registry` package: `ResolvePackageFromName` to resolve a
slug (`aws`, `pulumi/aws`, `opentofu/1password/1password`) into a
registry package. It uses the structured errors introduced by the
previous commit.
- 41c64d6e62b24c36a7ed2718fdd3f7724a6728b8 Uses
`registry.ResolvePackageFromName` to resolve `pluginDownloadURLs` for
the `pulumi plugin install resource` command.

Fixes https://github.com/pulumi/home/issues/3990