Support `pulumi package add <registry ID>` (#19928)
> [!IMPORTANT]  
> This feature is experimental, and only enabled when
`PULUMI_EXPERIMENTAL=1` is set.

This PR adds support for using `pulumi package add <registry ID>`. As an
example:

```sh
pulumi package add opentofu/airbytehq/airbyte
```

```yaml
name: ian-test-python
runtime:
  name: python
  options:
    virtualenv: venv
packages:
  airbyte: opentofu/airbytehq/airbyte@0.13.0
  # Another example of a registry based provider, this one parameterized:
  random:
    source: pulumi/pulumi/terraform-provider
    version: 0.11.0
    parameters:
      - hashicorp/random
      - 3.6.3

```

This is compatible with `pulumi install`, which correctly regenerates
the SDK for the registry based provider.


## Merging

### Complications

Merging this PR will be a bit complicated, due to the inability to
update all package loaders at once:

Before this PR, `plugin.IsLocalPluginPath(ctx,
"opentofu/airbytehq/airbyte")` returned true. That means that binaries
that have linked the `sdk/go/common` (and specifically
[`plugin.NewContext`](https://github.com/pulumi/pulumi/blob/408d561e5faec3e66e87b72d8eed6e563458efae/sdk/go/common/resource/plugin/context.go#L57-L64))
believe that `airbyte: opentofu/airbytehq/airbyte@0.13.0` represents a
local package located at `${PROJECT_ROOT}/opentofu/airbytehq/airbyte`.
Because `plugin.NewContext` validates that all path based packages exist
on creation, old binaries are unable to consume registry based
`Pulumi.yaml` files. They complain that the local binary path doesn't
exist:

    ```
    pulumi package add terraform-provider another/package
error: failed to get schema: GetSchema failed: rpc error: code = Unknown
desc = failed to create generator: could not make new context: no folder
at path '${PROJECT_ROOT}/opentofu/airbytehq/airbyte'
    ```

Unfortunately, `pulumi` isn't the only binary who which depends on
plugin loading. The above error is coming from the `terraform-provider`
code, specifically
[here](https://github.com/pulumi/pulumi-terraform-bridge/blob/49f3284e26fd004f03ac5e90a96136dea504d1da/pkg/tfgen/generate.go#L976-L979).

Building a new copy of `pulumi-terraform-provider` that links the
changes to `sdk/go/common` in this PR resolves the error.

### Recommendation

We should split this PR into two separate steps:

1. Update `sdk/go/common` now, with the changes in this PR. This will
make sources like `source/publisher/name` invalid as paths. Users can
adjust to the break by prefixing the path with `./`:
`./source/publisher/name` is a local path, and always will be.
2. After the first PR is released, update `pulumi-yaml`,
`terraform-provider` and `terraform-module` to depend on the new code.
3. After other dependents[^1] have been released, we can merge the other
half of this PR, updating package resolution to work with registry
slugs. At this point, upgrading `terraform-provider` and
`terraform-module` to latest will resolve all errors introduced with the
newest version of `pulumi package add`.


[^1]: We don't need to update all providers built with
`pulumi-terraform-bridge`, just those that do on-the-fly generation (and
thus require in-project plugin loading): the parametrizable providers.

## Merging - followup

The PR for step (1) merged 3 weeks ago:
https://github.com/pulumi/pulumi/pull/19930. There have been no reported
issues. The bridge update was delayed by
https://github.com/pulumi/pulumi/issues/19981, but
https://github.com/pulumi/pulumi-terraform-bridge/pull/3138 has now
merged.