Add --checksum to `pulumi plugin install` (#10528)
* Add --checksum to `pulumi plugin install`


With non-hex string:
```
$ pulumi plugin install resource gcp 6.35.0 --checksum boom
error: --checksum was not a valid hex string: encoding/hex: invalid byte: U+006F 'o'
```

With the wrong checksum:
```
$ pulumi plugin install resource gcp 6.35.0 --checksum c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d
[resource plugin gcp-6.35.0] installing
Downloading plugin: 44.08 MiB / 44.08 MiB [=========================] 100.00% 7s
error: [resource plugin gcp-6.35.0] downloading from : failed to download plugin: gcp-6.35.0: invalid checksum, expected c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9d, actual c58ade076e5b84aaeef154950e6b9b907341f0747163e3f299d3fc21594baa9c
```

Made the retry logic a bit smarter to not retry checksum failures (yes it _could_ be a network bit got flipped, but I think the UX is probably better here to not retry automatically)

* Add to CHANGELOG, fix typo in Close

* Don't error in Close

Don't actually need hash logic in close, we would of seen the error in Read and if we haven't read everything and are already closing it's probably because we hit some other error and so just want to exit out.

* Don't retry checksum errors