Resurrect analyzers
This change makes an initial pass at resurrecting our analyzers support.
For the most part, they actually continued to work just as before. I've
made numerous changes, however, to reach a new design, and to improve
the authoring experience for those using our JavaScript SDK.

For example, I can now run with my little test HIPAA compliance check:

    $ pulumi up --analyzer aws-hipaa
    error: analyzer 'aws-hipaa' reported an issue:
        Resource: urn:pulumi:clover-honey-ws::webserver::aws:ec2/securityGroup:SecurityGroup::web-secgrp
        Category: compliance; Severity: high
        Details: AWS resource 'web-secgrp' of type aws:ec2/securityGroup:SecurityGroup is not HIPAA eligible

This is still a work in progress, but is a consistent point where they
are functioning, so I'm landing it incrementally. Coming soon:

    1) The final shape of the SDK APIs.

    2) A new way of wiring analyzers into the engine, namely where
       they don't need to be inside the low-level deployment guts,
       and can instead use events subscribed to at the engine layer.

    2) Tests!